---
title: Config

collections:
  tools:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: tool

# Conversion
markdown            : CommonMarkGhPages

# theme: Minima

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]