---
title: Config

collections:
  tools:
    output: true
  templates:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: tool
  - scope:
      path: '_templates'
    values:
      layout: template

# Conversion
markdown            : Kramdown

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts: { line_numbers: table }

# theme: Minima

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]