---
title: Config

collections:
  tools:
    output: true
  templates:
    output: true
  articles:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: tool
  - scope:
      path: '_templates'
    values:
      layout: template
  - scope:
      path: '_articles'
    values:
      layout: article

# Conversion
markdown            : Kramdown

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # syntax_highlighter_opts: { line_numbers: table }

# theme: Minima

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]